version: "3"
services:
  slacker:
    build:
      context: ./slacker
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
    depends_on:
      - redis
    env_file:
    - .env
    volumes:
      - ./slacker:/slacker 
  worker:
    build:
      context: task-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
    - .env
  redis:
    image: redis
